In [1]:
import numpy as np

In [2]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
a.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [5]:
a.reshape(4,4)

ValueError: total size of new array must be unchanged

In [6]:
a.shape

(15L,)

In [7]:
a = a.reshape(3,5)

In [8]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
a.shape

(3L, 5L)

In [10]:
a.ndim

2

In [11]:
a.itemsie

AttributeError: 'numpy.ndarray' object has no attribute 'itemsie'

In [12]:
a.itemsie

AttributeError: 'numpy.ndarray' object has no attribute 'itemsie'

In [13]:
a.itemsize

4

In [14]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [15]:
np.zeros(3,4)

TypeError: data type not understood

In [16]:
np.zeros((3,4), dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [17]:
z = np.zeros((3,4), dtype=np.int32)

In [18]:
z.dtype

dtype('int32')

In [19]:
np.arange(10,30,10)

array([10, 20])

In [20]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [21]:
np.linspace(0, 2*np.pi, 100)

array([ 0.        ,  0.06346652,  0.12693304,  0.19039955,  0.25386607,
        0.31733259,  0.38079911,  0.44426563,  0.50773215,  0.57119866,
        0.63466518,  0.6981317 ,  0.76159822,  0.82506474,  0.88853126,
        0.95199777,  1.01546429,  1.07893081,  1.14239733,  1.20586385,
        1.26933037,  1.33279688,  1.3962634 ,  1.45972992,  1.52319644,
        1.58666296,  1.65012947,  1.71359599,  1.77706251,  1.84052903,
        1.90399555,  1.96746207,  2.03092858,  2.0943951 ,  2.15786162,
        2.22132814,  2.28479466,  2.34826118,  2.41172769,  2.47519421,
        2.53866073,  2.60212725,  2.66559377,  2.72906028,  2.7925268 ,
        2.85599332,  2.91945984,  2.98292636,  3.04639288,  3.10985939,
        3.17332591,  3.23679243,  3.30025895,  3.36372547,  3.42719199,
        3.4906585 ,  3.55412502,  3.61759154,  3.68105806,  3.74452458,
        3.8079911 ,  3.87145761,  3.93492413,  3.99839065,  4.06185717,
        4.12532369,  4.1887902 ,  4.25225672,  4.31572324,  4.37

In [32]:
mylist = [1., 2., 3., 4.]
mylist

[1.0, 2.0, 3.0, 4.0]

In [31]:
my_np_array = np.array([1, 2, 3, 4])
my_np_array

array([1, 2, 3, 4])

In [34]:
one_vector = np.ones(4)
one_vector

array([ 1.,  1.,  1.,  1.])

In [35]:
print one_vector

[ 1.  1.  1.  1.]


In [37]:
one_2d_array = np.ones((2,4))
print one_2d_array

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [38]:
zero_vector = np.zeros(4)
print zero_vector

[ 0.  0.  0.  0.]


In [39]:
empty_5x5 = np.empty((5,5))
print empty_5x5

[[  1.54126901e-316   3.76533041e-316   1.53367344e-316   3.76537310e-316
    1.86323024e-316]
 [  3.76541816e-316   1.53367344e-316   3.76533278e-316   1.86323024e-316
    3.76542053e-316]
 [  1.53367344e-316   3.76503239e-316   1.86323024e-316   3.76538021e-316
    1.53367344e-316]
 [  3.76529721e-316   1.86323024e-316   3.76529247e-316   1.53367344e-316
    3.76543713e-316]
 [  1.86323024e-316   3.73815917e-316   1.53367344e-316   3.76896911e-316
    1.54169509e-316]]


In [40]:
empty_5x5[0]

array([  1.54126901e-316,   3.76533041e-316,   1.53367344e-316,
         3.76537310e-316,   1.86323024e-316])

In [41]:
empty_5x5[0,1]

3.7653304128135075e-316

In [42]:
empty_5x5[0][1]

3.7653304128135075e-316

In [43]:
print empty_5x5[0:2]

[[  1.54126901e-316   3.76533041e-316   1.53367344e-316   3.76537310e-316
    1.86323024e-316]
 [  3.76541816e-316   1.53367344e-316   3.76533278e-316   1.86323024e-316
    3.76542053e-316]]


In [45]:
print empty_5x5[0:,4]

[  1.86323024e-316   3.76542053e-316   1.53367344e-316   3.76543713e-316
   1.54169509e-316]


In [46]:
select_index = np.array([True,False,True,False,False])

In [47]:
empty_5x5[0:,4][select_index]

array([  1.86323024e-316,   1.53367344e-316])

In [48]:
my_np_array

array([1, 2, 3, 4])

In [49]:
my_np_array*my_np_array

array([ 1,  4,  9, 16])

In [50]:
my_np_array - np.ones(4)

array([ 0.,  1.,  2.,  3.])

In [51]:
my_np_array**2

array([ 1,  4,  9, 16])

In [52]:
my_np_array.sum()

10

In [54]:
my_np_array.mean()

2.5

In [60]:
my_np_array.sum()/(1.0*len(my_np_array))

2.5

In [61]:
array1 = np.array([1., 2., 3., 4.])
array2 = np.array([2., 3., 4., 5.])
np.dot(array1, array2)

40.0

In [62]:
array1.dot(array2)

40.0

In [64]:
array2.dot(array1)

40.0

In [65]:
np.sqrt(np.dot(array1,array1))

5.4772255750516612

## predicted values

In [71]:
features = np.array([[1,2], [3,4], [5,6], [7,8]], dtype=float)
features

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.]])

In [72]:
weights = np.array([.4,.5])
weights

array([ 0.4,  0.5])

In [73]:
predictions = np.dot(features, weights)
predictions

array([ 1.4,  3.2,  5. ,  6.8])